#!/usr/bin/env python3
"""Dispatch one registered target as a supervised job with scope enforcement and a result envelope.

Blocking (short tasks, tests):
  dispatch.py <target> <label> <mode> <prompt-file> <artifact-root> <product-root>
Detached (long tasks; the orchestrator polls):
  dispatch.py start  <target> <label> <mode> <prompt-file> <artifact-root> <product-root>   -> prints {"job_id": ...}
  dispatch.py status <job-id>                      current state, progress, usage, resume time
  dispatch.py wait   <job-id> [--seconds N]        block up to N seconds (default 300) for a terminal state
  dispatch.py cancel <job-id>
  dispatch.py list
Other:
  dispatch.py health <target>
  dispatch.py usage  <target> [--refresh]          subscription usage windows and the suspend decision

There is no turn limit. A run stops only when it stalls (no output for idle_timeout_seconds), passes the wall-clock backstop
(max_wall_seconds, 0 disables), is cancelled, or crosses the usage guard. When a guarded usage window (five hour) drops below the
configured headroom, the job is suspended and its own session is resumed after the window resets. A blocking window (weekly)
stops the job for a human decision. Thresholds live in targets/stage-assignment-rules.toml.

The prompt file carries the scope as marker lines, generated by the controller from the recorded Execution Unit or assigned
artifact path:
  WORKFLOW_ARTIFACT_PATH=<artifact-root-relative path>      (artifact mode, exactly one)
  WORKFLOW_ALLOWED_PATH=<repo-relative path or dir/>        (zero or more; required in execution mode)
  WORKFLOW_RESULT_ARTIFACT_PATH=<artifact-root-relative>    (execution mode, at most one)
  WORKFLOW_VALIDATION_COMMAND=<exact command>               (execution mode, zero or more)

Environment:
  WORKFLOW_ROLE                     role being dispatched; targets not eligible for it are skipped
  WORKFLOW_FALLBACK_CHAIN           comma-separated recorded fallback targets, tried after an unavailable, unsuitable,
                                    usage-limited, or timed-out attempt
  WORKFLOW_STATE_DIR                job and usage state (default <shared root>/state)
  WORKFLOW_DISPATCH_TIMEOUT_SECONDS / WORKFLOW_IDLE_TIMEOUT_SECONDS / WORKFLOW_USAGE_HEADROOM   policy overrides
  CLAUDE_WORKER_MAX_TURNS           optional turn limit; unset means none
  CODEX_CLI_PATH                    Codex binary when it is not on PATH
  WORKFLOW_DISPATCH_ALLOW_MOCK=1 with WORKFLOW_DISPATCH_MOCK_COMMAND / WORKFLOW_USAGE_MOCK_FILE   test-only doubles
"""

from __future__ import annotations

import collections
import datetime
import hashlib
import json
import os
from pathlib import Path
import queue
import re
import signal
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
import uuid

import usage
from mini_toml import load


SHARED_ROOT = Path(__file__).resolve().parents[1]
TARGETS_ROOT = SHARED_ROOT / "targets"

SKIP_DIRS = {".git", "node_modules", ".turbo", ".next", ".nuxt", "dist", "build", "coverage", "__pycache__", ".venv", ".cache"}
HASH_LIMIT_BYTES = 5_000_000
TERMINAL = {"success", "failed", "timeout", "scope-violation", "unavailable", "unsuitable", "blocked", "cancelled", "invalid-dispatch",
            "permission-denied"}
EXIT_CODES = {"success": 0, "invalid-dispatch": 2, "unavailable": 3, "unsuitable": 3, "blocked": 4, "cancelled": 5,
              "scope-violation": 6, "permission-denied": 7, "timeout": 124, "running": 10, "queued": 10, "suspended": 11}
DENIAL = re.compile(r"requires approval|requested permissions|haven't granted|was blocked\. For security|permission to use .* has been denied",
                    re.IGNORECASE)
LIMIT_HIT = re.compile(r"usage limit|limit reached|hit your limit|rate limit|try again at", re.IGNORECASE)
RESUME_NOTE = ("Your previous session was interrupted by a pause (usage window or restart). Re-read the task and its scope, "
               "inspect the current state of the files in scope, and continue from where you stopped. Do not redo completed work.")


# ---------------------------------------------------------------- registry, scope, health (unchanged behaviour)

def targets() -> dict:
    records = {}
    for path in TARGETS_ROOT.glob("*.toml"):
        if path.name != "stage-assignment-rules.toml":
            record = load(path)
            records[record["id"]] = record
    return records


def resolve_target(target_id: str) -> dict:
    for canonical_id, record in targets().items():
        if target_id == canonical_id or target_id in record.get("legacy_aliases", []):
            return record
    raise ValueError("unknown target: %s" % target_id)


def mock_command() -> str | None:
    command = os.environ.get("WORKFLOW_DISPATCH_MOCK_COMMAND")
    if command and os.environ.get("WORKFLOW_DISPATCH_ALLOW_MOCK") != "1":
        raise ValueError("WORKFLOW_DISPATCH_MOCK_COMMAND requires WORKFLOW_DISPATCH_ALLOW_MOCK=1")
    return command or None


def snapshot(root: Path) -> dict[str, str]:
    """Hash regular files under root, skipping VCS metadata and dependency/build directories."""
    result: dict[str, str] = {}
    for directory, dirnames, filenames in os.walk(root):
        dirnames[:] = [name for name in dirnames if name not in SKIP_DIRS]
        for name in filenames:
            path = Path(directory) / name
            if path.is_symlink() or not path.is_file():
                continue
            relative = path.relative_to(root).as_posix()
            stat = path.stat()
            if stat.st_size <= HASH_LIMIT_BYTES:
                result[relative] = hashlib.sha256(path.read_bytes()).hexdigest()
            else:
                result[relative] = "size:%d:mtime:%d" % (stat.st_size, stat.st_mtime_ns)
    return result


def markers(prompt: str, name: str) -> list[str]:
    return re.findall(r"^%s=(.+)$" % name, prompt, re.MULTILINE)


def checked_relative(values: list[str]) -> set[str]:
    for value in values:
        if not value or Path(value).is_absolute() or ".." in Path(value).parts:
            raise ValueError("scope markers must be non-empty repository-relative paths")
    return set(values)


class Scope:
    """Write scope per repository root, derived from the prompt's marker lines."""

    def __init__(self, prompt: str, mode: str, artifact_root: Path, product_root: Path):
        self.validation_commands = markers(prompt, "WORKFLOW_VALIDATION_COMMAND")
        allowed = checked_relative(markers(prompt, "WORKFLOW_ALLOWED_PATH"))
        artifact = checked_relative(markers(prompt, "WORKFLOW_ARTIFACT_PATH"))
        result = checked_relative(markers(prompt, "WORKFLOW_RESULT_ARTIFACT_PATH"))
        if mode == "artifact":
            if len(artifact) != 1:
                raise ValueError("artifact mode requires exactly one WORKFLOW_ARTIFACT_PATH marker")
            if result:
                raise ValueError("WORKFLOW_RESULT_ARTIFACT_PATH is only valid in execution mode")
            self.writable = {artifact_root: allowed | artifact}
            self.read_only = [] if product_root == artifact_root else [product_root]
        else:
            if artifact:
                raise ValueError("WORKFLOW_ARTIFACT_PATH is only valid in artifact mode")
            if len(result) > 1:
                raise ValueError("execution mode accepts at most one WORKFLOW_RESULT_ARTIFACT_PATH marker")
            if not allowed:
                raise ValueError("execution mode requires at least one WORKFLOW_ALLOWED_PATH marker")
            self.writable = {product_root: set(allowed)}
            if result:
                self.writable.setdefault(artifact_root, set()).update(result)
            self.read_only = []
        self.file_count = sum(len(paths) for paths in self.writable.values())

    def roots(self) -> list[Path]:
        return list(self.writable) + list(self.read_only)

    def changed(self, before: dict[Path, dict[str, str]], after: dict[Path, dict[str, str]]) -> list[str]:
        return sorted(
            "%s:%s" % (root.name, path)
            for root in self.roots()
            for path in set(before[root]) | set(after[root])
            if before[root].get(path) != after[root].get(path)
        )

    def violations(self, before: dict[Path, dict[str, str]], after: dict[Path, dict[str, str]]) -> list[str]:
        found = []
        for root in self.roots():
            allowed = self.writable.get(root, set())
            for path in set(before[root]) | set(after[root]):
                if before[root].get(path) == after[root].get(path):
                    continue
                if path in allowed or any(entry.endswith("/") and path.startswith(entry) for entry in allowed):
                    continue
                found.append("%s:%s" % (root.name, path))
        return sorted(found)

    def context_bytes(self, product_root: Path) -> int:
        total = 0
        for path in self.writable.get(product_root, set()):
            candidate = product_root / path
            if candidate.is_file():
                total += candidate.stat().st_size
        return total


def binary_for(target: dict) -> str | None:
    if target["engine"] == "claude-code":
        return usage.find_binary("claude", "claude-cli.toml")
    if target["engine"] == "codex-cli":
        return usage.codex_binary()
    return None


def child_environment(**extra: str) -> dict:
    """Environment for a target process. Claude finds its Keychain login through USER, which stripped shells omit."""
    import getpass
    environment = dict(os.environ, **extra)
    environment.setdefault("USER", getpass.getuser())
    environment.setdefault("LOGNAME", environment["USER"])
    return environment


def health(target: dict) -> tuple[bool, str]:
    """Check that the target can be dispatched now. Mock mode skips live checks."""
    if mock_command():
        return True, "mock target"
    if target["engine"] in {"claude-code", "codex-cli"}:
        binary = binary_for(target)
        if not binary:
            return False, "%s binary not found" % target["engine"]
        try:
            completed = subprocess.run([binary, "--version"], capture_output=True, text=True, timeout=15, check=False,
                                       env=child_environment())
            if completed.returncode == 0 and target["engine"] == "claude-code":
                auth = subprocess.run([binary, "auth", "status"], capture_output=True, text=True, timeout=20, check=False,
                                      env=child_environment())
                if not json.loads(auth.stdout or "{}").get("loggedIn"):
                    return False, ("claude is not logged in for this process. A sandboxed parent (for example a Codex agent "
                                   "with sandbox_mode other than danger-full-access) cannot read the login Keychain; "
                                   "run the dispatch from an unsandboxed shell.")
        except (OSError, subprocess.TimeoutExpired, ValueError) as error:
            return False, "version check failed: %s" % error
        return completed.returncode == 0, (completed.stdout or completed.stderr).strip()[:200]
    base_url = target.get("ollama_base_url", "").rstrip("/")
    try:
        with urllib.request.urlopen(base_url + "/api/tags", timeout=5) as response:
            names = {model.get("name") for model in json.loads(response.read()).get("models", [])}
    except (urllib.error.URLError, OSError, ValueError) as error:
        return False, "Ollama unreachable: %s" % error
    model = target.get("model", "")
    if model not in names and (":" in model or model + ":latest" not in names):
        return False, "model %s not installed" % model
    return True, "model %s available" % model


def suitability(target: dict, role: str | None, prompt: str, scope: Scope, product_root: Path) -> tuple[bool, str]:
    if role and role not in target["eligible_roles"]:
        return False, "role %s is not eligible for %s" % (role, target["id"])
    limits = target["hard_limits"]
    if scope.file_count > limits["max_files"]:
        return False, "%d files exceeds max_files %d" % (scope.file_count, limits["max_files"])
    if len(prompt) > limits["max_prompt_chars"]:
        return False, "prompt of %d chars exceeds max_prompt_chars %d" % (len(prompt), limits["max_prompt_chars"])
    context = scope.context_bytes(product_root)
    if context > limits["max_context_bytes"]:
        return False, "%d context bytes exceeds max_context_bytes %d" % (context, limits["max_context_bytes"])
    return True, "within registered limits"


def permission_settings(target: dict) -> dict:
    return {"profile": "developer", "write_roots": [], "tools": ["Read", "Glob", "Grep"], "max_permission_denials": 3,
            **target.get("permissions", {})}


def claude_settings(scope: Scope, target: dict | None = None) -> str:
    """Claude permission rules, from the target's permission profile.

    developer: registered tools (Bash included) run freely and Edit/Write are allowed under every write root and scope root,
    so a run is not denied mid-way and usage is not wasted; the scope markers are verified after the run.
    scoped: edits only to the exact scope paths and Bash only for the routed validation commands.
    """
    permissions = permission_settings(target or {})
    if permissions["profile"] == "scoped":
        allow = ["Read", "Glob", "Grep"]
        for root, paths in scope.writable.items():
            for path in sorted(paths):
                pattern = "//%s/%s" % (str(root).lstrip("/"), path + "**" if path.endswith("/") else path)
                allow.extend(["Edit(%s)" % pattern, "Write(%s)" % pattern])
        allow.extend("Bash(%s)" % command for command in scope.validation_commands)
    else:
        allow = list(permissions["tools"])
        for root in sorted({str(path) for path in scope.roots()} | set(permissions["write_roots"])):
            allow.extend(["Edit(//%s/**)" % root.lstrip("/"), "Write(//%s/**)" % root.lstrip("/")])
    return json.dumps({"permissions": {"allow": allow, "defaultMode": "default"}}, sort_keys=True)


def writable_directories(target: dict, scope: Scope, write_root: Path, artifact_root: Path, product_root: Path) -> list[str]:
    """Directories the CLI must be told about; without them even allowed tools refuse to touch them."""
    roots = {str(path) for path in scope.roots()} | {str(artifact_root), str(product_root)}
    roots |= set(permission_settings(target).get("write_roots", []))
    return sorted(roots - {str(write_root)})


def target_command(target: dict, label: str, prompt_file: Path, prompt: str, scope: Scope, timeout: int,
                   artifact_root: Path, product_root: Path, write_root: Path, session: str | None,
                   resumed: bool) -> tuple[list[str], str | None]:
    """Return (argv, stdin text). With a session id the command resumes that session; without one a resumed run restarts the task."""
    text = RESUME_NOTE if session else (prompt + "\n\n" + RESUME_NOTE if resumed else prompt)
    if mock_command():
        return ["bash", "-c", mock_command()], None
    if target["engine"] == "claude-code":
        command = [binary_for(target) or "claude", "-p", "--output-format", "stream-json", "--verbose",
                   "--permission-mode", "default", "--settings", claude_settings(scope, target)]
        if os.environ.get("CLAUDE_WORKER_MAX_TURNS", "0") not in {"", "0"}:
            command.extend(["--max-turns", os.environ["CLAUDE_WORKER_MAX_TURNS"]])
        if session:
            command.extend(["--resume", session])
        for extra in writable_directories(target, scope, write_root, artifact_root, product_root):
            command.extend(["--add-dir", extra])
        return command, text
    if target["engine"] == "codex-cli":
        binary = binary_for(target) or "codex"
        if session:
            return [binary, "exec", "resume", "--json", "-c", 'sandbox_mode="workspace-write"', session, "-"], text
        command = [binary, "exec", "--json", "--sandbox", "workspace-write"]
        for extra in writable_directories(target, scope, write_root, artifact_root, product_root):
            command.extend(["--add-dir", extra])
        return command + ["-"], text
    command = ["python3", str(SHARED_ROOT / "mcp" / "local-worker" / "worker_cli.py"), target["id"], label,
               str(product_root), str(prompt_file), "--timeout-seconds", str(timeout)]
    for path in sorted(scope.writable.get(product_root, set())):
        command.extend(["--allowed-file", path])
    return command, None


# ---------------------------------------------------------------- job state

def jobs_root() -> Path:
    return usage.state_dir() / "jobs"


def write_json(path: Path, data: dict) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(data, indent=1, sort_keys=True), encoding="utf-8")
    os.replace(temporary, path)


class Job:
    def __init__(self, directory: Path):
        self.dir = directory
        self.state: dict = json.loads((directory / "state.json").read_text(encoding="utf-8")) if (directory / "state.json").is_file() else {}
        self.cancelled = threading.Event()
        self._touched = 0.0

    @classmethod
    def create(cls, spec: dict, prompt: str) -> "Job":
        stamp = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%S")
        directory = jobs_root() / ("%s-%s-%s" % (stamp, spec["target"], uuid.uuid4().hex[:4]))
        directory.mkdir(parents=True)
        (directory / "prompt.md").write_text(prompt, encoding="utf-8")
        write_json(directory / "spec.json", spec)
        job = cls(directory)
        job.update(job_id=directory.name, state="queued", target=spec["target"], label=spec["label"], mode=spec["mode"],
                   role=spec.get("role"), created_at=time.time(), turns=0, tool_calls=0, suspensions=[], attempts=[])
        return job

    @property
    def spec(self) -> dict:
        return json.loads((self.dir / "spec.json").read_text(encoding="utf-8"))

    def update(self, **fields) -> None:
        self.state.update(fields)
        self.state["updated_at"] = time.time()
        write_json(self.dir / "state.json", self.state)

    def touch(self, **fields) -> None:
        """Progress update, written at most every two seconds."""
        self.state.update(fields)
        if time.time() - self._touched >= 2:
            self._touched = time.time()
            self.update()

    def log(self, line: str) -> None:
        with open(self.dir / "events.jsonl", "a", encoding="utf-8") as handle:
            handle.write(line[:2000].rstrip("\n") + "\n")


def find_job(job_id: str) -> Job:
    directory = Path(job_id) if Path(job_id).is_dir() else jobs_root() / job_id
    if not (directory / "state.json").is_file():
        raise ValueError("unknown job: %s" % job_id)
    return Job(directory)


def alive(pid: int | None) -> bool:
    if not pid:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


# ---------------------------------------------------------------- one streamed attempt

def kill_group(process: subprocess.Popen) -> None:
    for sig, grace in ((signal.SIGTERM, 5), (signal.SIGKILL, 5)):
        try:
            os.killpg(process.pid, sig)
        except OSError:
            return
        try:
            process.wait(timeout=grace)
            return
        except subprocess.TimeoutExpired:
            continue


def summarize(block: dict) -> str:
    if block.get("type") == "tool_use":
        hint = block.get("input", {})
        detail = str(hint.get("file_path") or hint.get("command") or hint.get("pattern") or hint.get("path") or "")
        if detail.startswith("/") and len(detail) > 70:
            detail = "..." + detail[-67:]
        return ("%s %s" % (block.get("name", "tool"), detail)).strip()[:160]
    return ""


class Attempt:
    """Streams one process, tracks progress and usage, and stops it on stall, wall-clock, cancel, or usage guard."""

    def __init__(self, job: Job, target: dict, command: list[str], stdin: str | None, cwd: Path, environment: dict, rules: dict):
        self.job, self.target, self.rules = job, target, rules
        self.engine = target["engine"]
        self.session: str | None = None
        self.result_event: dict | None = None
        self.error_text = ""
        self.last_message = ""
        self.tail: collections.deque = collections.deque(maxlen=60)
        self.decision: dict | None = None
        self.denied = False
        self.max_denials = int(permission_settings(target)["max_permission_denials"])
        self.command, self.stdin, self.cwd, self.environment = command, stdin, cwd, environment

    def handle(self, line: str) -> None:
        self.tail.append(line.rstrip("\n"))
        self.job.log(line)
        if not line.startswith("{"):
            return
        try:
            event = json.loads(line)
        except ValueError:
            return
        state = self.job.state
        if self.engine == "claude-code":
            self.session = event.get("session_id") or self.session
            kind = event.get("type")
            if kind == "assistant":
                blocks = (event.get("message") or {}).get("content") or []
                calls = [summarize(block) for block in blocks if isinstance(block, dict) and block.get("type") == "tool_use"]
                texts = [block.get("text", "") for block in blocks if isinstance(block, dict) and block.get("type") == "text"]
                state["turns"] = state.get("turns", 0) + 1
                state["tool_calls"] = state.get("tool_calls", 0) + len(calls)
                self.job.touch(last_activity=(calls[-1] if calls else (texts[-1][:160] if texts else state.get("last_activity"))),
                               last_event_at=time.time(), session_id=self.session)
            elif kind == "rate_limit_event":
                windows = usage.windows_from_claude_event(event)
                if windows:
                    usage.record("claude-code", windows)
                    self.job.touch(usage=windows)
                    decision = usage.decide(windows)
                    self.decision = decision if decision["action"] != "ok" else None
            elif kind == "user":
                for block in (event.get("message") or {}).get("content") or []:
                    if not isinstance(block, dict) or block.get("type") != "tool_result" or not block.get("is_error"):
                        continue
                    content = block.get("content")
                    text = content if isinstance(content, str) else json.dumps(content)
                    if DENIAL.search(text):
                        denials = state.get("permission_denials", []) + [text[:300]]
                        self.job.touch(permission_denials=denials[-10:], permission_denial_count=len(denials))
                        self.denied = self.max_denials > 0 and len(denials) >= self.max_denials
            elif kind == "result":
                self.result_event = event
        elif self.engine == "codex-cli":
            kind = event.get("type")
            if kind == "thread.started":
                self.session = event.get("thread_id")
            elif kind == "turn.started":
                state["turns"] = state.get("turns", 0) + 1
            elif kind in {"item.started", "item.completed"}:
                item = event.get("item") or {}
                if item.get("type") == "command_execution":
                    state["tool_calls"] = state.get("tool_calls", 0) + (kind == "item.started")
                    self.job.touch(last_activity=("ran " + str(item.get("command", "")))[:160])
                elif item.get("type") == "agent_message":
                    self.last_message = item.get("text", "") or self.last_message
                    self.job.touch(last_activity=self.last_message[:160])
            elif kind in {"error", "turn.failed"}:
                self.error_text = str((event.get("error") or {}).get("message") or event.get("message") or "")
            self.job.touch(last_event_at=time.time(), session_id=self.session)

    def run(self) -> dict:
        rules, job = self.rules, self.job
        wall = rules["local_max_wall_seconds"] if self.engine == "ollama-aider" else rules["max_wall_seconds"]
        idle = 0 if self.engine == "ollama-aider" else rules["idle_timeout_seconds"]
        process = subprocess.Popen(self.command, cwd=self.cwd, env=self.environment, text=True, bufsize=1,
                                   stdin=subprocess.PIPE if self.stdin is not None else subprocess.DEVNULL,
                                   stdout=subprocess.PIPE, stderr=open(job.dir / "stderr.log", "ab"), start_new_session=True)
        job.update(pid_child=process.pid, state="running")
        if self.stdin is not None:
            def feed() -> None:
                try:
                    process.stdin.write(self.stdin)
                    process.stdin.close()
                except (OSError, ValueError):
                    pass
            threading.Thread(target=feed, daemon=True).start()
        lines: queue.Queue = queue.Queue()

        def read() -> None:
            for line in process.stdout:
                lines.put(line)
            lines.put(None)
        threading.Thread(target=read, daemon=True).start()

        started = last_event = last_poll = time.time()
        kind = "exit"
        while True:
            now = time.time()
            if job.cancelled.is_set():
                kind = "cancelled"
            elif wall and now - started > wall:
                kind = "wall"
            elif idle and now - last_event > idle:
                kind = "idle"
            elif self.denied:
                kind = "permission-denied"
            elif self.decision:
                kind = "usage-blocked" if self.decision["action"] == "blocked" else "usage-suspend"
            elif self.engine == "codex-cli" and not mock_command() and now - last_poll > rules["usage_poll_seconds"]:
                last_poll = now
                windows = usage.read_codex_windows()
                if windows:
                    usage.record("codex-cli", windows)
                    job.touch(usage=windows)
                    decision = usage.decide(windows)
                    self.decision = decision if decision["action"] != "ok" else None
                continue
            if kind != "exit":
                kill_group(process)
                break
            try:
                line = lines.get(timeout=1)
            except queue.Empty:
                continue
            if line is None:
                break
            last_event = time.time()
            self.handle(line)
        process.wait()
        returncode = process.returncode
        result_text = (self.result_event or {}).get("result", "")
        text = self.error_text or (result_text if isinstance(result_text, str) else "")
        failed = returncode != 0 or bool((self.result_event or {}).get("is_error"))
        if kind == "exit" and failed and LIMIT_HIT.search(text or "\n".join(self.tail)):
            kind = "usage-limit-hit"
        return {"kind": kind, "returncode": returncode, "session": self.session, "decision": self.decision,
                "stdout": json.dumps(self.result_event) if self.result_event else "\n".join(self.tail)[-4000:],
                "summary": ((self.result_event or {}).get("result") or self.last_message or "")[:2000]}


# ---------------------------------------------------------------- job execution

def sleep_until(job: Job, epoch: float) -> bool:
    """Sleep until epoch while keeping the job heartbeat fresh. False when cancelled."""
    while time.time() < epoch:
        if job.cancelled.wait(timeout=min(5, max(0.1, epoch - time.time()))):
            return False
        job.touch(heartbeat_at=time.time())
    return True


def preflight_usage(target: dict) -> dict:
    """Usage decision for a subscription target before starting; unknown usage never blocks."""
    if target["engine"] not in {"claude-code", "codex-cli"}:
        return {"action": "ok"}
    if mock_command() and usage.mock_usage(target["engine"]) is None:
        return {"action": "ok"}
    return usage.decide(usage.current(target["engine"]))


def run_candidate(job: Job, target: dict, label: str, mode: str, prompt_file: Path, prompt: str, scope: Scope,
                  artifact_root: Path, product_root: Path, rules: dict) -> dict:
    """Run one target to a final result, suspending across usage windows and resuming the same session."""
    write_root = artifact_root if mode == "artifact" else product_root
    session: str | None = None
    resumes = 0
    while True:
        command, stdin = target_command(target, label, prompt_file, prompt, scope, int(rules["local_max_wall_seconds"]),
                                        artifact_root, product_root, write_root, session, resumed=resumes > 0)
        environment = child_environment(WORKFLOW_SHARED_ROOT=str(SHARED_ROOT), WORKFLOW_TARGET_ID=target["id"],
                                        WORKFLOW_RESUME_SESSION=session or "", WORKFLOW_RESUME_COUNT=str(resumes))
        attempt = Attempt(job, target, command, stdin, write_root, environment, rules)
        result = attempt.run()
        session = result["session"] or session
        if result["kind"] in {"usage-suspend", "usage-limit-hit"}:
            if resumes >= int(rules["max_suspensions"]):
                result["kind"] = "exit"
                result["returncode"] = result["returncode"] or 1
                break
            decision = result["decision"] or {}
            resets_at = decision.get("resets_at")
            if not resets_at:
                windows = usage.current(target["engine"], refresh=True) or {}
                resets_at = (windows.get("five_hour") or {}).get("resets_at") or time.time() + 900
            resume_at = float(resets_at) + float(rules["resume_buffer_seconds"])
            entry = {"at": time.time(), "reason": result["kind"], "window": decision.get("window"), "resume_at": resume_at}
            job.update(state="suspended", resume_at=resume_at, suspensions=job.state.get("suspensions", []) + [entry])
            if not sleep_until(job, resume_at):
                result["kind"] = "cancelled"
                break
            job.update(state="running", resume_at=None)
            resumes += 1
            continue
        break
    result["session"] = session
    result["resumes"] = resumes
    return result


def outcome_of(result: dict) -> str:
    return {"cancelled": "cancelled", "wall": "timeout", "idle": "timeout", "usage-blocked": "blocked",
            "permission-denied": "permission-denied"}.get(
        result["kind"], "success" if result["returncode"] == 0 else "failed")


def relabel(label: str, primary: dict, target: dict) -> str:
    return target["label_prefix"] + label[len(primary["label_prefix"]):]


def execute(job: Job) -> dict:
    spec = job.spec
    primary = resolve_target(spec["target"])
    label, mode = spec["label"], spec["mode"]
    prompt_file = job.dir / "prompt.md"
    prompt = prompt_file.read_text(encoding="utf-8")
    artifact_root, product_root = Path(spec["artifact_root"]), Path(spec["product_root"])
    scope = Scope(prompt, mode, artifact_root, product_root)
    rules = usage.policy()
    role = spec.get("role")
    candidates = [primary] + [resolve_target(name) for name in spec.get("fallback_chain", [])]
    before = {root: snapshot(root) for root in scope.roots()}

    attempts: list[dict] = job.state.get("attempts", [])
    skipped: set[str] = set()
    final: dict | None = None
    blocked_note = None
    done = False
    for _ in range(int(rules["max_suspensions"]) + 1):
        waits: list[float] = []
        for candidate in candidates:
            if candidate["id"] in skipped:
                continue
            fits, reason = suitability(candidate, role, prompt, scope, product_root)
            if not fits:
                attempts.append({"target": candidate["id"], "outcome": "unsuitable", "reason": reason})
                skipped.add(candidate["id"])
                continue
            healthy, detail = health(candidate)
            if not healthy:
                attempts.append({"target": candidate["id"], "outcome": "unavailable", "reason": detail})
                skipped.add(candidate["id"])
                continue
            decision = preflight_usage(candidate)
            if decision["action"] == "blocked":
                attempts.append({"target": candidate["id"], "outcome": "blocked", "reason": "%s window used %.0f%%, resets %s" % (
                    decision["window"], decision["used"] * 100, datetime.datetime.fromtimestamp(decision["resets_at"]).isoformat(timespec="minutes"))})
                blocked_note = decision
                skipped.add(candidate["id"])
                continue
            if decision["action"] == "suspend":
                attempts.append({"target": candidate["id"], "outcome": "usage-limited", "resets_at": decision["resets_at"]})
                waits.append(float(decision["resets_at"]))
                continue
            job.update(current_target=candidate["id"], attempts=attempts)
            final = run_candidate(job, candidate, relabel(label, primary, candidate), mode, prompt_file, prompt, scope,
                                  artifact_root, product_root, rules)
            final["target_record"] = candidate
            attempts.append({"target": candidate["id"], "outcome": outcome_of(final), "resumes": final["resumes"]})
            if final["kind"] not in {"wall", "idle"}:
                done = True
                break
            skipped.add(candidate["id"])  # a stalled or overlong attempt may follow the recorded fallback chain
        if done or not waits:
            break
        resume_at = min(waits) + float(rules["resume_buffer_seconds"])
        job.update(state="suspended", resume_at=resume_at, attempts=attempts,
                   suspensions=job.state.get("suspensions", []) + [{"at": time.time(), "reason": "preflight", "resume_at": resume_at}])
        if not sleep_until(job, resume_at):
            final = {"kind": "cancelled", "returncode": 0, "session": None, "stdout": "", "summary": "", "resumes": 0,
                     "target_record": primary}
            break
        job.update(state="running", resume_at=None)

    after = {root: snapshot(root) for root in scope.roots()}
    if final is None:
        outcome = "blocked" if blocked_note else (attempts[-1]["outcome"] if attempts else "unavailable")
        outcome = "unavailable" if outcome == "usage-limited" else outcome
        final = {"kind": "exit", "returncode": None, "session": None, "stdout": "", "summary": "", "resumes": 0, "target_record": primary}
        envelope_outcome, exit_code = outcome, EXIT_CODES.get(outcome, 3)
    else:
        envelope_outcome = "scope-violation" if scope.violations(before, after) else outcome_of(final)
        exit_code = (final["returncode"] or 1) if envelope_outcome == "failed" else EXIT_CODES[envelope_outcome]
    target = final["target_record"]
    return {
        "job_id": job.dir.name, "target": target["id"], "engine": target["engine"], "label": relabel(label, primary, target),
        "mode": mode, "outcome": envelope_outcome, "exit_code": exit_code,
        "timeout_reason": {"wall": "wall-clock", "idle": "no output"}.get(final["kind"]),
        "changed_files": scope.changed(before, after), "scope_violation": scope.violations(before, after),
        "summary": final["summary"], "stdout": final["stdout"], "session_id": final["session"], "resumes": final["resumes"],
        "turns": job.state.get("turns", 0), "tool_calls": job.state.get("tool_calls", 0),
        "usage": job.state.get("usage"), "suspensions": job.state.get("suspensions", []),
        "permission_denials": job.state.get("permission_denials", []),
        "elapsed_seconds": round(time.time() - job.state["created_at"]), "attempts": attempts,
    }


def supervise(job: Job) -> dict:
    signal.signal(signal.SIGTERM, lambda *_: job.cancelled.set())
    signal.signal(signal.SIGINT, lambda *_: job.cancelled.set())
    job.update(supervisor_pid=os.getpid(), started_at=time.time(), state="running")
    try:
        envelope = execute(job)
    except (ValueError, OSError, KeyError, subprocess.SubprocessError) as error:
        envelope = {"job_id": job.dir.name, "outcome": "invalid-dispatch", "error": str(error), "exit_code": 2}
    write_json(job.dir / "result.json", envelope)
    job.update(state=envelope["outcome"], outcome=envelope["outcome"], exit_code=envelope["exit_code"], finished_at=time.time())
    return envelope


# ---------------------------------------------------------------- commands

def build_spec(argv: list[str]) -> tuple[dict, str]:
    mock_command()  # rejects a mock command without explicit opt-in before any job exists
    primary = resolve_target(argv[0])
    label, mode = argv[1], argv[2]
    mode = "artifact" if mode == "architecture" else mode
    if mode not in {"artifact", "execution"}:
        raise ValueError("mode must be artifact, architecture, or execution")
    if not label.startswith(primary["label_prefix"]):
        raise ValueError("label must start with %s" % primary["label_prefix"])
    prompt_file, artifact_root, product_root = Path(argv[3]).resolve(), Path(argv[4]).resolve(), Path(argv[5]).resolve()
    if not prompt_file.is_file() or not artifact_root.is_dir() or not product_root.is_dir():
        raise ValueError("prompt file, artifact root, and product root must exist")
    prompt = prompt_file.read_text(encoding="utf-8")
    Scope(prompt, mode, artifact_root, product_root)  # reject malformed scope before any job exists
    chain = [resolve_target(name.strip())["id"] for name in os.environ.get("WORKFLOW_FALLBACK_CHAIN", "").split(",") if name.strip()]
    spec = {"target": primary["id"], "label": label, "mode": mode, "artifact_root": str(artifact_root), "product_root": str(product_root),
            "role": os.environ.get("WORKFLOW_ROLE") or None, "fallback_chain": chain}
    return spec, prompt


def public_state(job: Job) -> dict:
    """State plus derived liveness. A dead supervisor on a non-terminal job is recorded as failed."""
    state = dict(job.state)
    if state["state"] not in TERMINAL and not alive(state.get("supervisor_pid")) and time.time() - state["updated_at"] > 20:
        job.update(state="failed", outcome="supervisor-lost", exit_code=1, finished_at=time.time())
        state = dict(job.state)
    now = time.time()
    state["elapsed_seconds"] = round((state.get("finished_at") or now) - state["created_at"])
    if state["state"] not in TERMINAL and state.get("last_event_at"):
        state["seconds_since_output"] = round(now - state["last_event_at"])
    if state.get("permission_denial_count"):
        state["warning"] = "%d permission denial(s); the run stops at the limit in the target's permissions.max_permission_denials" % state["permission_denial_count"]
    if state.get("resume_at"):
        state["resume_at_iso"] = datetime.datetime.fromtimestamp(state["resume_at"]).isoformat(timespec="minutes")
    state["poll_again_in_seconds"] = int(usage.policy()["status_poll_seconds"]) if state["state"] not in TERMINAL else 0
    return state


def exit_code_for(state: dict) -> int:
    return EXIT_CODES.get(state["state"], state.get("exit_code") or 1)


def command_start(argv: list[str], detach: bool) -> int:
    spec, prompt = build_spec(argv)
    job = Job.create(spec, prompt)
    if detach:
        log = open(job.dir / "supervisor.log", "ab")
        subprocess.Popen([sys.executable, str(Path(__file__).resolve()), "_supervise", str(job.dir)], stdin=subprocess.DEVNULL,
                         stdout=log, stderr=log, start_new_session=True, env=os.environ)
        print(json.dumps({"job_id": job.dir.name, "state": "queued", "job_dir": str(job.dir)}))
        return 0
    envelope = supervise(job)
    print(json.dumps(envelope, sort_keys=True))
    return envelope.get("exit_code", 1)


def command_wait(job_id: str, seconds: int) -> int:
    job = find_job(job_id)
    deadline = time.time() + seconds
    while True:
        job.state = json.loads((job.dir / "state.json").read_text(encoding="utf-8"))
        state = public_state(job)
        if state["state"] in TERMINAL or time.time() >= deadline:
            print(json.dumps(state, sort_keys=True))
            return exit_code_for(state)
        time.sleep(2)


def command_cancel(job_id: str) -> int:
    job = find_job(job_id)
    pid = job.state.get("supervisor_pid")
    if alive(pid):
        os.kill(pid, signal.SIGTERM)
        for _ in range(20):
            time.sleep(1)
            job.state = json.loads((job.dir / "state.json").read_text(encoding="utf-8"))
            if job.state["state"] in TERMINAL:
                break
    print(json.dumps(public_state(job), sort_keys=True))
    return 0


def command_list() -> int:
    rows = []
    for directory in sorted(jobs_root().glob("*"))[-15:] if jobs_root().is_dir() else []:
        try:
            state = public_state(Job(directory))
            rows.append({key: state.get(key) for key in ("job_id", "state", "target", "label", "elapsed_seconds", "last_activity")})
        except (OSError, ValueError, KeyError):
            continue
    print(json.dumps(rows, indent=1))
    return 0


def main(argv: list[str]) -> int:
    command = argv[1] if len(argv) > 1 else ""
    if command == "health" and len(argv) == 3:
        target = resolve_target(argv[2])
        healthy, detail = health(target)
        print(json.dumps({"target": target["id"], "healthy": healthy, "detail": detail}, sort_keys=True))
        return 0 if healthy else EXIT_CODES["unavailable"]
    if command == "usage" and len(argv) >= 3:
        return usage.main(["usage", resolve_target(argv[2])["engine"]] + argv[3:])
    if command == "start" and len(argv) == 8:
        return command_start(argv[2:], detach=True)
    if command == "status" and len(argv) == 3:
        job = find_job(argv[2])
        state = public_state(job)
        print(json.dumps(state, sort_keys=True))
        return exit_code_for(state)
    if command == "wait" and len(argv) in {3, 5}:
        return command_wait(argv[2], int(argv[4]) if len(argv) == 5 and argv[3] == "--seconds" else 300)
    if command == "cancel" and len(argv) == 3:
        return command_cancel(argv[2])
    if command == "list":
        return command_list()
    if command == "_supervise" and len(argv) == 3:
        supervise(Job(Path(argv[2])))
        return 0
    if len(argv) == 7:
        return command_start(argv[1:], detach=False)
    print(__doc__.split("\n\n")[0] + "\nRun with --help text in the module docstring for all commands.", file=sys.stderr)
    return 2


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv))
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        print(json.dumps({"outcome": "invalid-dispatch", "error": str(error)}), file=sys.stderr)
        raise SystemExit(2)
